### ISSUE TITLE
hostvars undefined in delegate_host (commit af46318c8e46245f950888502d72f0bdd3f07493)

### ISSUE THREAD

**Issue by SpitchAG** [OndrejHome/ansible.ha-cluster-pacemaker#12] opened 2020-09-11 13:01 UTC
seems that commit af46318c8e46245f950888502d72f0bdd3f07493 broke playbook, at least on my setup,
could be related to https://github.com/ansible/awx/issues/7725

setup:
CentOS Linux release 7.8.2003 (Core)

ansible 2.9.11
  config file = None
  configured module search path = ['/home/centos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by OndrejHome** [comment] 2020-09-12 01:39
Hi @SpitchAG,

Thank you for reporting this. I suspect that I have seen something similar during my testing, but was unable to reproduce it later on. Could you please also provide example on how your 'inventory' file looks like? Thank you.

**Comment by OndrejHome** [comment] 2020-09-13 08:21
Hi @SpitchAG,

I'm able to reproduce following error (which seems close enough - 'hostvar' in different )

~~~
==> ansible-2.9.11 <==
TASK [ondrejhome.ha-cluster-pacemaker : Get pcs status] ***************************************
fatal: [192.168.22.31]: FAILED! => {"msg": "'hostvars' is undefined"}

ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
~~~

~~~
==> ansible-2.9.12 <==
TASK [ondrejhome.ha-cluster-pacemaker : Get pcs status] ***************************************
ok: [192.168.22.31 -> {{ hostvars[delegate_host].ansible_host | default(delegate_host) }}]

ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
~~~

Doing further testing this seems to affect only ansible `2.9.10` and `2.9.11` in ansible `2.9.x` line. I have not tested older versions. In `devel` branch is code that should restrict the code that contains the code sensitive to this only to scenarios when remote nodes are needed - commit d1c6215e7dc7a98fc016f130d87a6f97df89d53c .

Please let me know if the version in `devel` resolves the situation for you. If not would it be possible to try updating ansible at least to version `2.9.12` and see if it is still present?

Once again thank you for reporting this!

**Comment by SpitchAG** [comment] 2020-09-14 13:21
i tried with this version:
ansible 2.9.13
  config file = None
  configured module search path = ['/home/centos/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


and it seems to be ok,
so i guess it has been fixed in newer version of ansible,
its ok for me to close the issue and force the use of a newest ansible version

**Comment by OndrejHome** [comment] 2020-09-15 13:06
Hi @SpitchAG ,
Thank you for confirmation and additional testing. There is no mechanism (to my knowledge) to force the use of latest ansible version. At best there is `min_ansible_version` in `meta/main.yml`, but it doesn't support minor version like `2.9.<something>`, only the `2.<something>`. I have therefore merged the change from `develop` that will reduce the use cases when this can be hit. The `README.md` also contains the note about that error, which would hopefully good enough.
The new version now has tag `25.1.0`.

Thank you again for reporting the issue and testing further the solution/workaround!
Will close this Github Issue now.

**Closed as completed by OndrejHome** 2020-09-15 13:06 UTC
Labels: bug
